@startuml node-bcc@v3

package node-bcc {
  class BCC {
    + {static} calculate(input: number[]|Buffer): Promise<number>
    + {static} calculateSync(input: number[]|Buffer): number
  }

  ' package stream {
  '   class BccStream
  ' }

  package util {
    class ASCII {
      + {static} asciiToByteArray(input: string): Promise<number[]>
      + {static} asciiToByteArraySync(input: string): number[]
      + {static} validate(input: string): boolean
    }

    class Hex {
      + {static} hexStringToByteArray(input: string): Promise<number[]>
      + {static} hexStringToByteArraySync(input: string): number[]
      + {static} validate(input: string, delimiter?: string, prefix?: string, suffix?: string): boolean
    }
  }
}

@enduml