sudo: required
addons:
  apt:
    packages:
    - ncftp
os:
- linux
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- '10'
before_install:
- npm set progress false
install:
- npm install
script:
- npm run tslint
- npm run build
- npm test
after_success:
- npm run codecov